package:
  name: mantid-framework
  version: {{ environ.get('MANTID_VERSION', '') }}

source:
  git_rev: {{ environ.get('GIT_REVISION', '') }}
  git_url: https://github.com/mantidproject/mantid.git

requirements:
  build:
      run_exports:
        strong:
          - boost {{ boost }}
          - nexus
          - numpy
          - poco
          - python {{ python }}
          - librdkafka
          - h5py
          - mkl
          - jsoncpp
          - gsl
        weak:
          - _openmp_mutex {{ _openmp_mutex }} [linux64]
          - blas
          - cmake
          - eigen
          - gxx_linux-64 8.* [linux64]
          - hdf4
          - hdf5
          - jemalloc
          - muparser
          - nexus
          - ninja
          - numpy
          - openblas
          - openssl
          - pkg-config
          - tbb-devel
          - mkl
          - liblapack {{ liblapack }}
          - pre-commit
  run:
    - _openmp_mutex {{ _openmp_mutex }} [linux64]
    - python-dateutil
    - pyyaml
    - scipy
    - six
    - tbb
    - muparser
    - blis

build:
  script_env:
    - CC
    - CXX
    - OSX_VERSION

test:
  imports:
    - mantid.kernel
    - mantid.geometry
    - mantid.api

about:
  home:
  license:
  license_file:
