schedules:
# Run at 4am on sundays
- cron: "0 4 * * 0"
  displayName: Weekly morning build
  branches:
    include:
    - main
  always: true

pr: none

trigger: none

extends:
  template: templates/build_and_package.yml
  parameters:
    publish: false # Do not publish package to anaconda cloud
    git_rev: "main"
    mantid_ver: "6.2.x" # unknown
