trigger:
  branches:
    exclude:
      - '*'

pr:
  autoCancel: true
  branches:
    include:
      - '*'

extends:
  template: templates/build_and_package.yml
  parameters:
    git_rev: "v6.2.0"
    mantid_ver: "6.2.0"
