trigger:
  branches:
    exclude:
      - '*'

pr:
  autoCancel: true
  branches:
    include:
      - '*'

extends:
  template: templates/build_and_package.yml
  parameters:
    git_rev: "a5dca387c0b88a0d6161ab54e76dfc3c99b2c83d"
    mantid_ver: "6.2.0"
