trigger:
  tags:
    include:
      - '*.*.*'

pr: none

extends:
  template: templates/build_and_package.yml
  parameters:
    publish: true #  publish package to anaconda cloud
    git_rev: "v6.3.0"
    mantid_ver: "6.3.0"
